from selenium.webdriver.common.by import By
class Selectors_List:
    FIRST_NAME = (By.ID, "firstname")
    LAST_NAME = (By.ID, "lastname")
    EMAIL = (By.ID, "email")
    PASSWORD = (By.ID, "pass")
    PASSWORD_CONFIRMATION = (By.ID, "password_confirmation")
    CREATE_AN_ACCOUNT_BTN = (By.XPATH, "//button[@class= 'action submit primary']")
    CREATE_AN_ACCOUNT_OPT = (By.XPATH, ['//a[@href = "https://magento.softwaretestingboard.com/customer/account/create/"]'])
    SIGN_IN_BTN = (By.ID, "send2")
    SIGN_IN_OPT = (By.XPATH, "//a[@href='https://magento.softwaretestingboard.com/customer/account/login/referer/aHR0cHM6Ly9tYWdlbnRvLnNvZnR3YXJldGVzdGluZ2JvYXJkLmNvbS8%2C/']")
    FORGET_YOUR_PASSWORD_BTN = (By.XPATH, "//a[@class= 'action remind and @href= https://magento.softwaretestingboard.com/customer/account/forgotpassword/']")
    EMAIL_ERROR = (By.XPATH, '//div[@class= "mage-error"]')
    PASSWORD_ERROR = (By.XPATH,  '//div[@class= "mage-error"]')
    RESET_MY_PASSWORD_BTN = (By.XPATH, "//button[@class= 'action submit primary']")
    CONFIRMATION_MESSAGE = (By.XPATH, '//div[@data-bind = "html: $parent.prepareMessageForHtml(message.text)"]')
    SEARCH_ENTIRE_HERE = (By.XPATH,'//input[@id = "search"]')
    CONSENT_BTN = (By.XPATH, '//p[@class = "fc-button-label"]')
    WAYFARER_MESSENGER_BAG_PRODUCT = (By.XPATH, '//img[@class = "product-image-photo"]')
    ADD_TO_CART_WAYFARER_MESSENGER_BAG = (By.XPATH, '//button[@type= "submit" and @title= "Add to Cart" and @class= "action tocart primary"]')
    ACTION_SHOWCART_WAYFARER_MESSENGER_BAG = (By.XPATH, '//a[@class="action showcart"]')
    PROCEED_TO_CHECKOUT = (By.XPATH, '//button[@id = "top-cart-btn-checkout"]')
    WHAT_IS_NEW_PAGE = (By.XPATH, 'https://magento.softwaretestingboard.com/what-is-new.html')
    COMPANY = (By.XPATH, '//input[@name = "company"]')
    STREET_ADDRESS = (By.XPATH, '//input[@name = "street[0]"]')
    CITY = (By.XPATH, '//input[@name = "city"]')
    STATE = (By.XPATH, '//select[@name = "region_id"]')
    POSTCODE = (By.XPATH,'//input[@name = "postcode"]')
    COUNTRY_ID = (By.XPATH, '//select[@name = "country_id"]')
    PHONE_NUMBER = (By.XPATH, '//input[@name = "telephone"]')
    SELECT_PRICE = (By.XPATH, '//input[@type = "radio"]')
    NEXT_BTN = (By.XPATH, '//button[@class = "button action continue primary"]')
    PLACE_ORDER_BTN = (By.XPATH, '//button[@title= "Place Order"]')
    CONTINUE_SHOPPING_BTN = (By.XPATH, '//a[@class = "action primary continue" and @href= "https://magento.softwaretestingboard.com/"]')
    WOMEN = (By.XPATH, '//span ["Women"]//span')
    TOPS = (By.XPATH, '//span ["Tops"]//span')
    HOODIES_SWEATSHIRTS = (By.XPATH, '//span ["Hoodies & Sweatshirts"]//span')
    SIZE = (By.ID,'option-label-size-143-item-166')
    COLOR = (By.ID, 'option-label-color-93-item-52')
    SET_DESCENDING_DIRECTION = (By.XPATH, '//a[@title= "Set Descending Direction"]')
    SET_ASCENDING_DIRECTION = (By.XPATH, '//a[@title= "Set Ascending Direction"]')
    SORTER = (By.XPATH, '//select[@id= "sorter"]')
    THIS_IS_A_REQUIRED_FIELD = (By.ID, 'customer-email-error')
    ERROR_VALIDATION_MESSAGE = (By.XPATH, '//span[@data-bind= "text: errorValidationMessage()"]')
    SIGN_IN_OPT_2 = (By.XPATH, '//button[@class="action action-auth-toggle"]')
    LOGIN_EMAIL = (By.ID, 'login-email')
    LOGIN_PASSWORD = (By.ID, 'login-password')
    SIGN_IN_BTN_2= (By.XPATH,'//button[@type= "submit"]')
    SHIPPING_ADDRESS_ITEM = (By.XPATH, '//div[@class= "shipping-address-item selected-item"]')
    SEARCH = (By.XPATH, '//input[@id= "search"]')
    WAYFARER_KEYWORD = (By.XPATH, '//span[@class= "base" and @data-ui-id= "page-title-wrapper"]')
    NEW_ADDRESS = (By.XPATH, '//button[@class = "action action-show-popup"]')
    SHIP_HERE = (By.XPATH, '//button[@class= "action primary action-save-address"]')
    GRID = (By.XPATH, '//a[@class= "modes-mode mode-grid"]')
    LIST = (By.XPATH, '//a[@class= "modes-mode mode-list"]')
    SALE_IMAGE = (By.XPATH, '//img[@src= "https://magento.softwaretestingboard.com/pub/media/wysiwyg/sale/sale-main.jpg"')
    TRAINING_IMAGE = (By.XPATH, '//img[@src= "https://magento.softwaretestingboard.com/pub/media/wysiwyg/training/training-main.jpg"')
    TRAINING_OPTION = (By.XPATH, '//a[@href = "https://magento.softwaretestingboard.com/training.html" and @class= "level-top ui-corner-all"]')
    SALE_OPTION = (By.XPATH, '//a[@href = "https://magento.softwaretestingboard.com/sale.html"]')
    MESSAGE_INFO = (By.XPATH, '//div[@class= "message info empty"]')
    VIDEO_DOWNLOAD_OPTION = (By.XPATH,'//a[@href = "https://magento.softwaretestingboard.com/training/training-video.html"]')
    PRODUCT_ITEM_LINK = (By.XPATH, '//a[@class="product-item-link"]')
    ADD_TO_CART_RADIANT_TEE = (By.XPATH, '(//button[@title= "Add to Cart"])[1]')

