from selenium.webdriver.common.by import By
class Selectors_List:
    FIRST_NAME = (By.ID, "firstname")
    LAST_NAME = (By.ID, "lastname")
    EMAIL = (By.ID, "email")
    PASSWORD = (By.ID, "pass")
    PASSWORD_CONFIRMATION = (By.ID, "password_confirmation")
    CREATE_AN_ACCOUNT_BTN = (By.XPATH, "//button[@class= 'action submit primary']")
    CREATE_AN_ACCOUNT_OPT = (By.XPATH, ['//a[@href = "https://magento.softwaretestingboard.com/customer/account/create/"]'])
    SIGN_IN_BTN = (By.ID, "send2")
    SIGN_IN_OPT = (By.XPATH, "//a[@href='https://magento.softwaretestingboard.com/customer/account/login/referer/aHR0cHM6Ly9tYWdlbnRvLnNvZnR3YXJldGVzdGluZ2JvYXJkLmNvbS8%2C/']")
    FORGET_YOUR_PASSWORD_BTN = (By.XPATH, "//a[@class= 'action remind and @href= https://magento.softwaretestingboard.com/customer/account/forgotpassword/']")
    EMAIL_ERROR = (By.XPATH, '//div[@class= "mage-error"]')
    PASSWORD_ERROR = (By.XPATH,  '//div[@class= "mage-error"]')
    RESET_MY_PASSWORD_BTN = (By.XPATH, "//button[@class= 'action submit primary']")
    CONFIRMATION_MESSAGE = (By.XPATH, '//div[@data-bind = "html: $parent.prepareMessageForHtml(message.text)"]')
    SEARCH_ENTIRE_HERE = (By.XPATH,'//input[@id = "search"]')
    CONSENT_BTN = (By.XPATH, '//p[@class = "fc-button-label"]')
    WAYFARER_MESSENGER_BAG_PRODUCT = (By.XPATH, '//img[@class = "product-image-photo"]')
    ADD_TO_CART_WAYFARER_MESSENGER_BAG = (By.XPATH, '//button[@type= "submit" and @title= "Add to Cart" and @class= "action tocart primary"]')
    ACTION_SHOWCART_WAYFARER_MESSENGER_BAG = (By.XPATH, '//a[@class="action showcart"]')
    PROCEED_TO_CHECKOUT = (By.XPATH, '//button[@id = "top-cart-btn-checkout"]')
    WHAT_IS_NEW_PAGE = (By.XPATH, 'https://magento.softwaretestingboard.com/what-is-new.html')
    COMPANY = (By.XPATH, '//input[@name = "company"]')
    STREET_ADDRESS = (By.XPATH, '//input[@name = "street[0]"]')
    CITY = (By.XPATH, '//input[@name = "city"]')
    STATE = (By.XPATH, '//select[@name = "region_id"]')
    POSTCODE = (By.XPATH,'//input[@name = "postcode"]')
    COUNTRY_ID = (By.XPATH, '//select[@name = "country_id"]')
    PHONE_NUMBER = (By.XPATH, '//input[@name = "telephone"]')
    SELECT_PRICE = (By.XPATH, '//input[@type = "radio"]')
    NEXT_BTN = (By.XPATH, '//button[@class = "button action continue primary"]')
    PLACE_ORDER_BTN = (By.XPATH, '//button[@title= "Place Order"]')
    CONTINUE_SHOPPING_BTN = (By.XPATH, '//a[@class = "action primary continue" and @href= "https://magento.softwaretestingboard.com/"]')
    WOMEN = (By.XPATH, '//span ["Women"]//span')
    TOPS = (By.XPATH, '//span ["Tops"]//span')
    HOODIES_SWEATSHIRTS = (By.XPATH, '//span ["Hoodies & Sweatshirts"]//span')
    SIZE = (By.ID,'option-label-size-143-item-166')
    COLOR = (By.ID, 'option-label-color-93-item-52')
    SET_DESCENDING_DIRECTION = (By.XPATH, '//a[@title= "Set Descending Direction"]')
    SET_ASCENDING_DIRECTION = (By.XPATH, '//a[@title= "Set Ascending Direction"]')
    SORTER = (By.XPATH, '//select[@id= "sorter"]')

